apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: anarchy-api
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "persistentvolumeclaims", "nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["kubevirt.io"]
    resources: ["virtualmachines"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["kubevirt.io"]
    resources: ["virtualmachineinstances", "kubevirts"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["cdi.kubevirt.io"]
    resources: ["datavolumes", "datasources", "cdis"]
    verbs: ["get", "list", "watch"]
