apiVersion: apps/v1
kind: Deployment
metadata:
  name: anarchy-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: anarchy-api
  template:
    metadata:
      labels:
        app: anarchy-api
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: anarchy-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: ANARCHY_API_ADDR
              value: ":8080"
            - name: ANARCHY_NAMESPACE
              value: "{{ .Values.config.namespace }}"
          readinessProbe:
            httpGet:
              path: /api/v1/system/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /api/v1/system/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 6
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
