image:
  repository: ghcr.io/popododo0720/anarchy-api
  tag: dev
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

serviceAccount:
  create: true
  name: anarchy-api

config:
  namespace: anarchy-system

imagePullSecrets: []

nodeSelector: {}

resources: {}

replicaCount: 1
